### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by mrniceguy051** [TheDutchMC04/HaroTorch#9]
I use PaperMC#700
I use Aikar's flag
And im on java 11.
There is no console spam before i think what happen is 
 after i install multiverse no spam but after placing haro torch on other world i think thats why.

![IMG_20210519_095822](https://user-images.githubusercontent.com/44065944/118745669-3e4a0200-b889-11eb-840e-989496bd53f9.jpg)

**Comment by TobiasDeBruijn** [comment]
Thats definitely interesting. Do you have the full stack trace for me from me the error? Then I can see what causes it 😃

**Comment by mrniceguy051** [comment]
> Thats definitely interesting. Do you have the full stack trace for me from me the error? Then I can see what causes it 😃

I don't know about stack trace but I think I can share you my logs. 
[2021-05-18-4.log](https://github.com/TheDutchMC/HaroTorch/files/6509587/2021-05-18-4.log)
And Also a pastebin for just a section of that Console Spam.
https://pastebin.com/TJBQNBY8

**Comment by mrniceguy051** [comment]
And I also tried reverting into version 2.2.0-9 and there is no Console Spam.

**Comment by TobiasDeBruijn** [comment]
That is exactly what I was looking for, thanks.

It's odd that the issue doesn't happen in 2.2.0-9, it **should**, since I haven't changed that bit of code. The issue occurs in a function that'll get the Torches near players. In this function itll attempt to get the current World of a Player.

I've done some googling, I think the issue occurs because the MultiVerse world hasn't been loaded yet. For now I've implemented a nullcheck that'll skip that Torch.

Could you try this development version for me to see if this fixes  your issue?: [Google drive](https://drive.google.com/file/d/1cv7dXRjbfaxVzAlLU43jWQ446g1eQyxb/view?usp=sharing)

**Comment by mrniceguy051** [comment]
Alright I'm wrong about the reverting into older version fix it. it's not and I think I found the problem.
When using [UltimateAutoRestart](https://www.spigotmc.org/resources/1-8-1-16-2k-users-ultimateautorestart-need-an-autorestart-plugin-grab-the-best-one-today.64414/) to restart my server and then when a player join and load area where the torch is place on the second world, the Spam begin. I have my logs you can see where the spam start, it was after a player joined and load the chunks where torch is in on second world.

The spam not showing when using the Normal Restart on Skynode Panel. But this spam problem start when I install Multiverse.

[2021-05-19-8.log](https://github.com/TheDutchMC/HaroTorch/files/6511183/2021-05-19-8.log)

And also the Dev version you send it doesn't fix the spam.

**Comment by TobiasDeBruijn** [comment]
I missed that there were two worlds used on that line, I added a nullcheck for one of them, but forgot the other. Try this one: https://drive.google.com/file/d/1dghVRlkrT5or8IuNXbbpYm2nB4UVAOpa/view?usp=sharing

**Comment by mrniceguy051** [comment]
> I missed that there were two worlds used on that line, I added a nullcheck for one of them, but forgot the other. Try this one: https://drive.google.com/file/d/1dghVRlkrT5or8IuNXbbpYm2nB4UVAOpa/view?usp=sharing

Yes, it's fixed now. Thank You

**Comment by TobiasDeBruijn** [comment]
Awesome. I'll include this in the next release then!

**Comment by TobiasDeBruijn** [comment]
Following your comment on [spigotmc.org](https://www.spigotmc.org/threads/harotorch.388338/page-3#post-4168565) I've got an updated one here.

Essentially all this changes is instruct Spigot to load HaroTorch *after* MultiVerse, so that we can guarantee that it's worlds are loaded.

You can find the updated jar [here](https://drive.google.com/file/d/1WzjD7mUttjhDhBm3RJXW-hrV0lfsQZKL/view?usp=sharing)

**Comment by mrniceguy051** [comment]
> Following your comment on [spigotmc.org](https://www.spigotmc.org/threads/harotorch.388338/page-3#post-4168565) I've got an updated one here.
> 
> Essentially all this changes is instruct Spigot to load HaroTorch _after_ MultiVerse, so that we can guarantee that it's worlds are loaded.
> 
> You can find the updated jar [here](https://drive.google.com/file/d/1WzjD7mUttjhDhBm3RJXW-hrV0lfsQZKL/view?usp=sharing)

Sorry for late reply, I tested this and my problem is fix now. Thank You again for fixing it.

**Comment by TobiasDeBruijn** [comment]
Awesome! I'll include this fix in the latest release then.

Thanks for reporting!
